os: linux
dist: focal
language: ruby
before_script:
  - gem install awesome_bot
script:
  - awesome_bot --version
  - awesome_bot --allow-redirect --allow-dupe --white-list "apt" `find . -name "*.md"`
