name: Awesome Bot

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  awesome_bot:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0

      - name: Installing awesome_bot
        run: gem install awesome_bot

      - name: Checking links with awesome_bot
        run: |
          awesome_bot --version
          awesome_bot --allow-redirect --allow-dupe --white-list "apt" `find . -name "*.md"`
