name: Broken Link Checker
on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"
jobs:
  site_link_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: "14"

      - name: Installing Broken Link Checker
        run: npm install broken-link-checker -g

      - name: Check for Broken Links
        run: |
          blc --version
          blc https://til.jugalkishore.me -ro
